version: "3.8"
services:
  dev-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: get-testimonials
      POSTGRES_PASSWORD: get-testimonials
      POSTGRES_DB: get-testimonials
